// <auto-generated />
using System;
using EmployeeDetails.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeDetails.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180926000427_AddedNullableColumn")]
    partial class AddedNullableColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeDetails.API.Models.Employees", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Basesalary")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<decimal>("C401k")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<decimal>("Dental")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<decimal>("Medical")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<decimal?>("TakeHome")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<decimal>("Vision")
                        .HasColumnType("decimal(9, 2)");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
